### ISSUE TITLE
Documentation to review

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.RavenDB#355] opened 2017-10-05 13:27 UTC
The following doco article needs to be reviewed within the time frame of the next release

* [x] https://docs.particular.net/persistence/ravendb
* [x] https://docs.particular.net/persistence/ravendb/manual-dtc-settings
* [x] https://docs.particular.net/persistence/ravendb/outbox
  * [x] Make "Effect on DocStore" section (all DTC info) a <V5 partial https://github.com/Particular/docs.particular.net/pull/3376
* [x] https://docs.particular.net/persistence/ravendb/connection
* [x] https://docs.particular.net/persistence/ravendb/subscription-versioning
* [x] https://docs.particular.net/persistence/ravendb/reroute-existing-timeouts
  * [x] Version 1 & 2 missing bullets
* [x] https://docs.particular.net/persistence/upgrades/ravendb-4to5
* [x] https://docs.particular.net/persistence/upgrades/ravendb-3to4
* [x] https://docs.particular.net/persistence/ravendb/installation
* [x] https://docs.particular.net/persistence/ravendb/version-compatibility
* [x] https://docs.particular.net/persistence/ravendb/uninstalling-v4
* [x] https://docs.particular.net/persistence/ravendb/licensing
* [x] https://docs.particular.net/persistence/ravendb/saga-concurrency
* [x] https://docs.particular.net/persistence/ravendb/dtc
* [x] https://docs.particular.net/persistence/ravendb/operations-scripting
* [x] https://docs.particular.net/samples/ravendb/simple/
* ~~https://docs.particular.net/samples/saga/ravendb-custom-sagafinder/~~ *Sample removed by https://github.com/Particular/docs.particular.net/pull/3581*
  * ~~V3 version wants `[Unique]` on saga data, but is using unique bundle~~
* ~~DTC warning should really not appear on V5~~ *Not much we can do since engine won't allow for a partial inside an include*
* [x] Update [RavenDB persistence index page](https://docs.particular.net/persistence/ravendb/) to mention the new tenant aware support https://github.com/Particular/docs.particular.net/pull/3897
* ~~One update to reset review date on all these pages~~

**Comment by mauroservienti** [comment] 2017-10-12 09:31
Should we update [this](https://docs.particular.net/persistence/ravendb/?version=raven_5#distributed-transaction-coordinator-settings) to state that DTC is not anymore supported in NServiceBus.RavenDB V5?

**Comment by mauroservienti** [comment] 2017-10-16 16:07
Does this statement still hold true?

![image](https://user-images.githubusercontent.com/1325611/31622474-cd43495e-b29c-11e7-83ac-bfb8c34c1de2.png)

**Comment by mauroservienti** [comment] 2017-10-16 16:12
https://docs.particular.net/persistence/ravendb/reroute-existing-timeouts has formatting issues, I basically cannot read it 😄

**Comment by DavidBoike** [comment] 2017-10-16 19:43
The warning about ResourceManagerId definitely does not hold true. It's been replaced by the DTC is unreliable warning where applicable. You don't run into it in CoreV6+ samples at all because Learning Transport won't support DTC. https://github.com/Particular/docs.particular.net/pull/3356 removes it completely.

I did note that the V3 saga finder sample is busted because the Raven code wants to force a `[Unique]` attribute on _something_ but only the unique constraints bundle stuff is on there. Not sure what to do about that. Added a PoA item.

I have _no idea_ what's going on with the fields partial in reroute-existing-timeouts.

**Comment by DavidBoike** [comment] 2017-10-24 18:49
Fixed the fields partial in reroute-existing-timeouts. It had one space between UL outline levels - perhaps that displayed correctly with the JavaScript-based Markdown engine, but not under Markdig.

Now the issue is that the v1-2 versions contain no partial, and so are incomplete:

* https://docs.particular.net/persistence/ravendb/reroute-existing-timeouts?version=raven_2
* https://docs.particular.net/persistence/ravendb/reroute-existing-timeouts?version=raven_1

But we don't support either of those versions, so what do we do?

**Comment by DavidBoike** [comment] 2017-10-24 18:54
Updated the PoA with issues I found as sub items. Also added that the DTC warning should really not appear on V5, but the problem is that it's an include, and includes can't have version-specific partials. Yet we also don't want to put version specific partials (<= 4) on every single page.

**Comment by DavidBoike** [comment] 2017-10-24 19:26
Manual DTC settings seems good to go as far as I know. (Checking it off.) I had to update its metadata to be only versions `[,5)` since it doesn't apply in 5, and remove corresponding V5 snippets.

**Comment by DavidBoike** [comment] 2017-10-24 20:24
Fixed up the Outbox document by removing the section on "what it does to the DocStore" in V5, which was all about DTC and no longer relevant. Checked that off.

Checked off Connection Options. Already the stuff about connection strings was partial'ed out, but I noticed that the description of why we prefer an external DocStore was "because DTC settings" which is no longer true, but we still prefer external DocStore, and even in older versions it's no longer about getting "safe" DTC settings, so I changed the description for all versions rather than introducing a new partial.

Added a checkbox at the end of the PoA to just adjust the review date for all these docs (as one commit) when we're about to close this issue.

That's all I have energy for today.

**Comment by mauroservienti** [comment] 2018-02-26 16:35
Re

>  Update 4->5 upgrade guide to mention the new tenant aware support

Do we want to mention it in the upgrade guide or is https://github.com/Particular/docs.particular.net/pull/3636 good enough?

**Comment by mauroservienti** [comment] 2018-05-22 04:37
Withdrawn the last PoA item as it’ll be handled by the docs maintenance ongoing process.
There’s only one item left. WE CAN GET THIS DONE 😄

**Comment by mauroservienti** [comment] 2018-06-26 15:42
Raised https://github.com/Particular/docs.particular.net/pull/3897 to kill the last PoA item.

**Closed** 2018-06-29 16:08 UTC
