### ISSUE TITLE
Tests not cleaning up databases after running

### ISSUE THREAD

**Issue by bording** [Particular/NServiceBus.RavenDB#116] opened 2015-11-13 18:21 UTC
While working on hotfix 3.0.6, I saw that the acceptance tests were failing on the build server with the following error:

`Microsoft.Isam.Esent.Interop.EsentLogDiskFullException: Log disk full`

The build agent's disk was full with RavenDB database files, so it appears that the tests are not correctly cleaning up after themselves.

**Comment by danielmarbach** [comment] 2015-11-16 06:26
That problem should be fixed in develop.

https://github.com/Particular/NServiceBus.RavenDB/blob/develop/src/NServiceBus.RavenDB.AcceptanceTests/Config.cs#L32

I think the problem is related to master and hotfix branches.

**Comment by andreasohlund** [comment] 2015-11-16 10:15
The script that we have today cleans by:
```

[Reflection.Assembly]::LoadWithPartialName("System.Messaging")
$q = new-object -ComObject  MSMQ.MSMQQueueInfo
$queues = [System.Messaging.MessageQueue]::GetPrivateQueuesByMachine("localhost")
$queues | % { 
	$q.FormatName = $_.FormatName
	$q.Delete()	
}
$remainingQueues = [System.Messaging.MessageQueue]::GetPrivateQueuesByMachine("localhost")
if($remainingQueues.Count -gt 0)
{
    Write-Host "Unable to cleanup all queues"
    $remainingQueues | % { 
	    Write-Host $_.FormatName
    }
    exit 1
}
Restart-Service RavenDB
```

Notice the restart of the service. I remember that we setup raven to clean on startup perhaps we can use that trick for now? (I assume the newer versions of raven haven't been configured to do this) cc @gbiellem

**Comment by danielmarbach** [comment] 2015-11-16 10:21
@andreasohlund restarting RavenDB doesn't change a thing. The storage taken by esent will still be taken. We need to cleanup the databases by the tests (like we do on develop) or switch to embedded RavenDB as proposed by @SimonCropp

**Comment by andreasohlund** [comment] 2015-11-16 10:32
No I remember, we where running the server in InMemory mode, that's why the restart worked. Is that an option?

**Comment by bording** [comment] 2015-11-16 16:57
@danielmarbach A similar `Cleanup()` also exists on master.
https://github.com/Particular/NServiceBus.RavenDB/blob/master/src/NServiceBus.RavenDB.AcceptanceTests/Config.cs#L28

However, if you look at the TC build log, the `"Deleted '{0}' database"` output never shows up. As far as I can tell, `Cleanup()` is never actually being called. I've also debugged the tests on the master branch locally, and the breakpoint I had on the method was never hit.

I also just tried the same thing on develop, and it does appear that `Cleanup()` is being called there. What has changed on develop to make this be called there?

**Comment by danielmarbach** [comment] 2015-11-16 19:02
@bording

The first implementation was done by me on develop of NServiceBus in the
`ConfigureExtensions`. I then adopted those extensions on develop of
NSB.RavenDB. Keeping them in sync turned out to be too cumbersome that's
why we decided to remove those from master but left the cleanup methods for
future purpose. Now that I think back probably not the best decision...

**Comment by kbaley** [comment] 2016-02-25 14:42
I think this has been mitigated to a large degree. Databases are cleaned up for successful tests. Failed ones still stick around ( @colin-higgins can confirm ). 

With that in mind, does this still need to be tagged Core v6? /cc @mauroservienti

**Comment by mauroservienti** [comment] 2016-02-25 16:38
> With that in mind, does this still need to be tagged Core v6

No, if this https://github.com/Particular/NServiceBus/pull/3514 fixes also the scenario with tests failures we can safely close this one.

**Comment by colin-higgins** [comment] 2016-02-25 17:09
A failed or errored test does not mean the database will stick around... it MIGHT in edge cases, but I'm in favor of closing as well.

So, here goes.

**Comment by colin-higgins** [comment] 2016-04-29 13:51
Closing in favor of: https://github.com/Particular/NServiceBus.RavenDB/issues/84

**Closed by colin-higgins** 2016-04-29 13:51 UTC
