### ISSUE TITLE
Duplicate Subscriptions

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.RavenDB#281] opened 2016-09-14 09:36 UTC
The subscription storage is expected to replace existing subscriptions with new subscriptions of the same address/messagetype. The current implementation seems to keep the existing subscription around which can lead to duplicate events being dispatched in scale-out scenarios.

<details>
<summary>Repro test, also available here: https://github.com/Particular/NServiceBus.RavenDB/commit/8999b17ad9a16078ae0a2ba5f698e347cd577b49</summary>
```
    [Test]
    public async Task should_overwrite_existing_subscription()
    {
        const string subscriberAddress = "testEndPoint@localhost";
        var messageType = new MessageType("SomeMessageType", "1.0.0.0");

        var storage = new SubscriptionPersister(store);
        await storage.Subscribe(new Subscriber(subscriberAddress, "old"), messageType, new ContextBag());
        await storage.Subscribe(new Subscriber(subscriberAddress, "new"), messageType, new ContextBag());

        var subscriber = (await storage.GetSubscriberAddressesForMessage(new[]
        {
            messageType
        }, new ContextBag())).ToArray();

        Assert.AreEqual(1, subscriber.Length);
        Assert.AreEqual(subscriberAddress, subscriber[0].TransportAddress);
        Assert.AreEqual("new", subscriber[0].Endpoint);
    }
```
</details>

ping @Particular/ravendb-persistence-maintainers 

At first glance, this seems to be bug which needs to be fixed before the RTM.

**Comment by mauroservienti** [comment] 2016-09-14 10:34
Are we saying that the second parameter of the `Subscriber` constructor is not part of the subscription key, but the subscriber address + message type are the only things we should use to track a subscription? Correct? (in which case this is a bug.)

**Comment by mauroservienti** [comment] 2016-09-14 10:36
And here is the bug: https://github.com/Particular/NServiceBus.RavenDB/blob/develop/src/NServiceBus.RavenDB/Subscriptions/SubscriptionClient.cs#L24

**Comment by timbussmann** [comment] 2016-09-14 11:28
@mauroservienti I don't think the equality implementation itself is the bug. The issue is this part: https://github.com/Particular/NServiceBus.RavenDB/blob/release-4.0.0/src/NServiceBus.RavenDB/Subscriptions/SubscriptionPersister.cs#L59 which does only add subscriptions instead of replacing them.

**Comment by mauroservienti** [comment] 2016-09-14 12:31
Agree @timbussmann but the root cause if that the [`Contains`](https://github.com/Particular/NServiceBus.RavenDB/blob/release-4.0.0/src/NServiceBus.RavenDB/Subscriptions/SubscriptionPersister.cs#L57) returns `false` since the comparison is done via that `Equals` implementation that takes the Endpoint name into account. So the implementation states that the endpoint name is part of the key along with the transport address.

**Comment by mauroservienti** [comment] 2016-09-15 13:52
This is waiting for @weralabaj to check what is the NHibernate behavior

**Comment by weralabaj** [comment] 2016-09-16 08:24
NHibernate ignores endpoint name, only takes into account transport address and message type (see https://github.com/Particular/NServiceBus.NHibernate/blob/release-7.0.0/src/NServiceBus.NHibernate/Subscriptions/SubscriptionPersister.cs#L32 and https://github.com/Particular/NServiceBus.NHibernate/blob/release-7.0.0/src/NServiceBus.NHibernate/Subscriptions/Subscription.cs).

@Particular/nservicebus-maintainers can you confirm that the following assumption is always correct:

> the subscriber address + message type are the only things we should use to track a subscription?

Won't that be a problem with new routing? Meaning will be the transport address identical after migration in all cases (scaleout, callbacks, etc.)?

**Comment by timbussmann** [comment] 2016-09-16 15:00
@weralabaj the transport address should not change after a migration. The endpoint name is a value to identify scaled out instances which have different addresses, but belong to the same scaled out logical endpoint.

so yes, the address + message type are sufficient as an identifier, but the endpoint name needs to be updated. When Subscriber(x[address], t[message type], a[logical endpoint]) unsubscribes, it should even remove the subscription if the storage only has Subscriber(x, t, b). the logical endpoint name at migration time will be null for v5 endpoints and after a migration endpoints will subscribe with a logical endpoint in the subscription. This also means, that a Subscription for (x, t, null) needs to be updated/replaced when a Subscription(x, t, a) comes in.

**Comment by weralabaj** [comment] 2016-10-03 07:59
Resolved in https://github.com/Particular/NServiceBus.RavenDB/pull/284

**Closed** 2016-10-03 09:08 UTC
Labels: Size: S, Type: Bug
