### ISSUE TITLE
RavenDB can raise ConcurrencyException with DTC even though saga document cannot be modified concurrently

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.RavenDB#279] opened 2016-09-08 11:42 UTC
I just got the following exception when DTC is enabled:

> Raven.Abstractions.Exceptions.ConcurrencyException: Document XXX/2b71aa6b-d060-4bdb-b373-a67b00d13e3c is being modified by another transaction: Raven.Database.Impl.DTC.ChangedDoc

The writing to the same saga instance in the corresponding test cannot happen concurrently. The test is this https://github.com/Particular/NServiceBus.RavenDB/issues/278

Not using DTC resolves this issue.

**Comment by mauroservienti** [comment] 2016-09-14 07:41
@ramonsmits 

> The writing to the same saga instance in the corresponding test cannot happen concurrently

What guarantees that? (thinking out loud) Because that exception states that 2 different `sessions` tried to write to the same document, and one write attempt was rolled back do to conflicting transactions. How can it be the same GUID?

**Comment by ramonsmits** [comment] 2016-09-14 08:08
Not sure I understand your question @mauroservienti . The test modifies a saga instance document sequentially. So no overlapping/concurrent writes to the same saga instance are possible.

That is guaranteed by the fact that the message contains the saga instance ID and that ID is only present in ONE message. When that message is processed, the same message is sent.

Seeding/Creation of the messages:

- https://github.com/Particular/EndToEnd/blob/master/src/PerformanceTests/Common/Scenarios/SagaUpdate/SagaUpdateRunner.cs#L12-L23

Processing of the messages:

- https://github.com/Particular/EndToEnd/blob/master/src/PerformanceTests/Common/Scenarios/SagaUpdate/SagaUpdateRunner.V6.cs#L16-L22

**Comment by mauroservienti** [comment] 2016-09-14 10:41
Is this happening with all the transports? As said the only things that comes to mind, so far, is that the incoming message for whatever reason is processed multiple times in parallelcausing the saga to be created more than than once, and obviously only one will succeed.

**Comment by ramonsmits** [comment] 2016-09-14 13:53
Yes, I understand your reasoning and if that was the case then I didn't create the issue :-). I didn't try this with the SQL transport but this doesn't happen with MSMQ and NHibernate persistence.

**Comment by mauroservienti** [comment] 2016-09-14 14:08
understood, thanks, much better the problem is here than in Core :smile: 
Let me recap what I understood so far:

* the test sends a bunch of messages to start new sagas
* each message carries a different unique identifier
* the above means that sending 100 messages must create 100 different sagas

Do you have an option to provide the full error message? Or at least disclose that `XXX` in the error message:

> Raven.Abstractions.Exceptions.ConcurrencyException: Document XXX/2b71aa6b-d060-4bdb-b373-a67b00d13e3c is being modified by another transaction: Raven.Database.Impl.DTC.ChangedDoc

Given that you are using nested classes I have the suspicion that the "document" that is failing is not the saga data document but the Unique property Document that we create to correlate sagas given that your tests correlate on a custom property. I still fail in seeing the connection, though.

Is there any option that the seeding process ends up in generating commands with duplicated identifiers?

**Comment by DavidBoike** [comment] 2016-09-15 14:21
This is to be expected with DTC transactions on RavenDB. The database is not fully updated when the transaction commits in code. So the next message from the SendLocal may start processing before the transaction is fully committed on the server, resulting in this exception.

**Closed by DavidBoike** 2016-09-15 14:21 UTC
