### ISSUE TITLE
NServiceBus 5.x and RavenDb 3.5.2 compatibility

### ISSUE THREAD

**Issue by pekkah** [Particular/NServiceBus.RavenDB#300] opened 2017-01-27 07:23 UTC
I just finished downgrading to RavenDb.Client 3.0.30155 after attempting 3.5.2. With the newer version I was getting missing method exceptions from saga persister get method from ravendb query.

Is there a combination of RavenDb 3.5.2 client that will work with NServiceBus 5.x? We're trying to go around a bug in RavenDb client where the bug is fixed in 3.5.2.

**Comment by DavidBoike** [comment] 2017-01-27 14:58
Hi @pekkah!

Thanks for getting in touch. There are definitely breaking changes in the Raven client between 3.0.30155 and 3.5.2 - you can see an [API comparison between the two versions using our API Comparer tool here](http://apicomparer-preview.particular.net/compare/RavenDB.Client/3.0.30155...3.5.2#.NETFramework,Version=v4.5).

Which methods specifically are missing that are causing trouble?

This is the current version matrix for RavenDB support:

| NServiceBus | NServiceBus.RavenDB | RavenDB |
|:-----------:|:-------------------:|:-------:|
|     5.x     |         2.x         |   2.5   |
|     5.x     |         3.x         |   3.0   |
|     6.x     |        4.0.x        |   3.0   |
|     6.x     |        4.1.x        |   3.5   |

So no, we don't have a version that explicitly supports NServiceBus 5.x together with RavenDB 3.5.

Also, what is the Raven bug you're trying to get around by using 3.5.2?

**Comment by pekkah** [comment] 2017-01-28 09:40
This is what made me believe that the 3.5.2 version of the client would work
https://www.nuget.org/packages/NServiceBus.RavenDB/3.0.12

> Dependencies
> NServiceBus (>= 5.2.8 && < 6.0.0)
> RavenDB.Client (>= 3.0.3800 && < 4.0.0)

The bug is related to RavenDb unable to load "metrics" assembly from its internal resources. This bug is fixed on 3.5.2 and hotfix version of 3.0.x but as the hotfix is marked with -Hotfix NuGet treats it as a prerelease and doesn't like it when it's bundled with stable version of our internal NuGets. Also 3.5.2 includes some other improvements that we would like to get also to the client side.

**Comment by pekkah** [comment] 2017-01-28 09:49
I haven't double checked but I think this is the line causing the missing method exception:
`https://github.com/Particular/NServiceBus.RavenDB/blob/support-3.0/src/NServiceBus.RavenDB/SagaPersister/SagaPersister.cs#L86`

Of course there might be more but that's the first I hit.
I'll double check it on Monday at the office.

**Comment by DavidBoike** [comment] 2017-01-30 19:23
@pekkah I've confirmed what is happening with a local repro.

In 3.5, Raven moved the methods for `First`, `FirstOrDefault`, `Single`, and `SingleOrDefault` from `IDocumentQueryBase<T, out TSelf>` to `IDocumentQuery<T>` which happens to implement the former interface.

So, if you were writing the `FirstOrDefault` code in Visual Studio and upgraded to Raven 3.5, the compiler would figure it out and link to the new method. But, the NServiceBus.RavenDB code is statically compiled and so it is looking specifically for the method on the base interface, where it is now missing.

There's no way we can statically compile a DLL that will work with both Raven 3 and Raven 3.5. However the references are defined, it will be broken on the other version.

The nuspec range that goes up to 4.0.0 is something that was determined (hopefully?) before Raven 3.5 was released, and now that the package is out there, we can't change it. We're considering releasing a 3.0.13 update where the only change would be the dependency metadata in the nuspec file.

**Comment by DavidBoike** [comment] 2017-02-01 17:29
@pekkah have you reached any resolution on this issue? Would a good avenue be to ask RavenDB to release the hotfix build as a non-prerelease NuGet? If so we can ask on your behalf.

**Comment by pekkah** [comment] 2017-02-02 08:38
We are planning for update to v6 but it would be great to get a "stable" release of ravendb 3.0.x so we don't run into that metrics bug anymore.

**Comment by mauroservienti** [comment] 2017-02-02 09:13
@pekkah are you using any version of `Metrics` and/or `Metrics.NET` directly in your project?

**Comment by pekkah** [comment] 2017-02-02 09:15
Nope. The only version is the one embedded into Ravendb.

**Comment by DavidBoike** [comment] 2017-02-02 20:04
From [this post from Oren on the RavenDB Google Group](https://groups.google.com/forum/#!searchin/ravendb/hotfix%7Csort:relevance/ravendb/cqUpAh1J9HQ/LLIHs6EcFQAJ), 3.0 is in Hotfix-only mode, although:

> We'll still have stable release, which will basically be an accumulation of fixes. The idea is that unless you are impacted by the issue, you don't need to upgrade.
> 
> Hotfix release are going through the same rigor of a stable release, and are supported for production usage. 

So eventually, they may bundle up the last 5 hotfixes (current count) into a new stable release. Until then, you can use the hotfix version in production.

So @pekkah it would appear your options are to use the Hotfix NuGet package, or if you want to upgrade to 3.5, you'd have to upgrade to NServiceBus 6 as well.

I do have to say I'm a bit confused by your statement (emphasis mine):

> This bug is fixed on 3.5.2 and hotfix version of 3.0.x but as the hotfix is marked with -Hotfix NuGet treats it as a prerelease and _**doesn't like it when it's bundled with stable version of our internal NuGets**_. 

Why not? What happens?

**Comment by pekkah** [comment] 2017-02-03 09:40
@DavidBoike nuget pack will fail if your nuget references prerelease nuget packages and your nuget is not prerelease. This also has been changed into warning lately, but at least currently is still throwing an error on VSO builds.

**Comment by DavidBoike** [comment] 2017-02-06 19:48
Looks like a new Raven release [should be coming out this week](https://groups.google.com/d/msg/ravendb/cqUpAh1J9HQ/S1muojDVAwAJ). :smiley:

As that should fix the issue, I'm going to close it. Thanks @pekkah for raising!

**Closed by DavidBoike** 2017-02-06 19:48 UTC

**Comment by pekkah** [comment] 2017-02-07 06:49
Thanks for the support 👍

**Comment by pekkah** [comment] 2017-03-27 13:36
@DavidBoike thanks for the mug ;)

**Comment by frankclaassens** [comment] 2017-04-09 18:24
@DavidBoike At the moment, are there hotfixes by either Particular or Raven that could allow for a platfom to run using NServiceBus 5.x, NServiceBus.RavenDB 3.0.x & RavenDB 3.5.3. This is our tech stack atm.

We were using NServiceBus.RavenDB 3.0.12 hence why the nuget incompatibiliy was never highlighted (I believe this was a bug that Particular corrected in 3.0.13), but being months into the upgrade process, it would be extremely hard to simply upgrade to NServiceBus 6.x.

What are my options here?

**Comment by DavidBoike** [comment] 2017-04-10 16:20
@frankclaassens In the works: https://github.com/Particular/NServiceBus.RavenDB/pull/311

We had hoped that 3.5 would be compatible and we could avoid a separate minor version, but the binary incompatibility makes that impossible. That's why up through 3.0.12 had < 4.0 in the nuspec, which we had to change to reflect reality in 3.0.13. Our policy now is to be conservative in only accepting 1 minor version in the nuspec and expanding the scope later if it by chance "just works."

**Comment by DavidBoike** [comment] 2017-04-10 21:00
@frankclaassens NServiceBus.RavenDB 3.2.0 has now been released and is on NuGet.
