### ISSUE TITLE
Remove the server version check in all the RavenDB packages

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.RavenDB#142] opened 2016-01-26 16:05 UTC
RavenDB 3.0 in the latest builds changed the way the server version is returned to the client, this is breaking actual production version of `NServiceBus.RavenDB` since we expect the version to have a different format.

Details: https://groups.google.com/forum/#!topic/ravendb/DkdELIaPz7U

//cc @dvdstelt @SimonCropp @colin-higgins

**Comment by dvdstelt** [comment] 2016-01-27 07:14
They're reverting back to the original format, but as Ayende states it's just there for informational purposes. So they might change it again.

**Comment by mauroservienti** [comment] 2016-01-27 07:36
We cannot relay on something like that, as Oren said the purpose of that
API is to display a string in the Studio, so they are free to change it as
they like.
Since we already removed the version check in the latest develop I propose
that we remove it in all production versions and document the compatibility
matrix we support.

On Wed, Jan 27, 2016 at 8:14 AM Dennis van der Stelt <
notifications@github.com> wrote:

> They're reverting back to the original format, but as Ayende states it's
> just there for informational purposes. So they might change it again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/NServiceBus.RavenDB/issues/142#issuecomment-175456352>
> .
>
-- 
Mauro Servienti | Solution Architect | Particular Software

**Comment by SimonCropp** [comment] 2016-02-17 04:19
@mauroservienti @DavidBoike seems the PR was merged. so should this be closed?

**Comment by DavidBoike** [comment] 2016-02-17 14:40
Hasn't been released. I wouldn't call it done done.

**Comment by johnsimons** [comment] 2016-02-18 03:40
> Hasn't been released. I wouldn't call it done done.

So you saying that we can't close issues until they have been released ?
It doesn't make sense to me, especially if we are tracking progress.
I would think that once doco is up to date and code PR is merged the issue is done, releasing is a different can of worms (especially for a major release, where there has to be a vast amount of coordination).

**Comment by mauroservienti** [comment] 2016-02-18 06:04
I agree with @johnsimons, what is missing here is a link to a milestone that is the thing that should keep track of what needs to be released.

**Comment by DavidBoike** [comment] 2016-03-04 14:30
OK, this is implemented in 4, and went out in 3.1.0 (was included in release notes) and although that got pulled, it will "go out again" in 3.1.1. So based on that I'm satisfied it's "done done".

**Closed by DavidBoike** 2016-03-04 14:30 UTC
Labels: State: In Progress, Tag: Core v6

**Comment by DavidBoike** [comment] 2016-03-28 19:17
This check will be included in 3.0.7
